<?php

namespace AP\StockBundle\Repository;

/**
 * stockoperationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class stockoperationRepository extends \Doctrine\ORM\EntityRepository
{
}
