ap_caisse_homepage:
    path:     /caisse
    defaults: { _controller: APCaisseBundle:Default:index }

ap_caisse_table:
    path:     /caisse/{id}
    defaults: { _controller: APCaisseBundle:Default:table }

ap_caisse_commande:
    path:     /commande/{prod}/{id}
    defaults: { _controller: APCaisseBundle:Default:commande }
    requirements:
            prod : .+
    options:
            expose: true

ap_caisse_ticket:
    path:     /ticket/{id}/{mode}/{total}
    defaults: { _controller: APCaisseBundle:Default:ticket }
    options:
            expose: true

ap_caisse_detail_ticket:
    path:     /ticket/details/{id}
    defaults: { _controller: APCaisseBundle:Default:detail }

ap_caisse_detail_vendeur:
    path:     /detail/vendeur/{id}/{total}/{from}/{to}/{espece}/{orange}/{carte}
    defaults: { _controller: APCaisseBundle:Default:detailvendeur }

ap_caisse_detail_vendeur_print:
    path:     /detail/print/vendeur/{id}/{total}/{from}/{to}/{espece}/{orange}/{carte}
    defaults: { _controller: APCaisseBundle:Default:detailvendeurprint }

ap_caisse_cloture:
    path:     /cloture/{id}/{from}/{to}
    defaults: { _controller: APCaisseBundle:Default:cloture }
