<?php

namespace AP\CaisseBundle\Repository;

/**
 * boncommandeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class boncommandeRepository extends \Doctrine\ORM\EntityRepository
{
}
