<?php

namespace AP\CaisseBundle\Repository;

/**
 * commandeprodRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class commandeprodRepository extends \Doctrine\ORM\EntityRepository
{


    public function getByDate($from,$to)
    {

        $qb = $this->createQueryBuilder("e");
        $qb
            ->andWhere('e.date BETWEEN :from AND :to')
            ->orderBy("e.date", 'DESC')
            ->setParameter('from', $from )
            ->setParameter('to', $to)
        ;
        $result = $qb->getQuery()->getResult();

        return $result;
    }


}
