<?php

namespace AP\CaisseBundle\Repository;

/**
 * commandeprodRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class commandeprodRepository extends \Doctrine\ORM\EntityRepository
{
}
