<?php

namespace AP\CaisseBundle\Repository;

/**
 * commandeprodRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class commandeprodRepository extends \Doctrine\ORM\EntityRepository
{


    public function getByDate($from,$to)
    {

        $qb = $this->createQueryBuilder("e");
        $qb
            ->andWhere('e.date BETWEEN :from AND :to')
            ->orderBy("e.date", 'DESC')
            ->setParameter('from', $from )
            ->setParameter('to', $to)
        ;
        $result = $qb->getQuery()->getResult();

        return $result;
    }



    public function getByBons($bons)
    {

        $qb = $this->createQueryBuilder("e");
        $qb
            ->select("SUM(e.quantite) AS qte,IDENTITY(e.produit) AS prod,IDENTITY(e.bon) AS bon")
            ->Where('e.bon = :bons' )


            ->groupBy('e.produit')
            ->setParameter('bons', $bons )


        ;
        $tickets = $qb->getQuery()->getResult();

        return $tickets;
    }



}
