<?php

namespace AP\CaisseBundle\Repository;

/**
 * tablesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class tablesRepository extends \Doctrine\ORM\EntityRepository
{
}
