<?php

namespace AP\UsersBundle\Repository;

/**
 * employesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class employesRepository extends \Doctrine\ORM\EntityRepository
{
}
