fournisseur_index:
    path:     /
    defaults: { _controller: "APProductsBundle:fournisseur:index" }
    methods:  GET

fournisseur_show:
    path:     /{id}/show
    defaults: { _controller: "APProductsBundle:fournisseur:show" }
    methods:  GET

fournisseur_new:
    path:     /new
    defaults: { _controller: "APProductsBundle:fournisseur:new" }
    methods:  [GET, POST]

fournisseur_edit:
    path:     /{id}/edit
    defaults: { _controller: "APProductsBundle:fournisseur:edit" }
    methods:  [GET, POST]

fournisseur_delete:
    path:     /{id}/delete
    defaults: { _controller: "APProductsBundle:fournisseur:delete" }
    methods:  DELETE
