<?php

namespace AP\ProductsBundle\Entity;

/**
 * mediadocRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class thumbnailRepository extends \Doctrine\ORM\EntityRepository
{
}

